version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
