name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.1, 8.2 ]
        stability: [ prefer-lowest, prefer-stable ]

    name: ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --no-scripts

      - name: Update composer dependencies
        uses: php-actions/composer@v6
        with:
          command: update --${{ matrix.stability }}

      - name: Execute tests
        run: composer test
